# Permalinks
permalink:           pretty

# Setup
title:               Prajwal Gurumurthy
tagline:             ""
url:                 http://prajwalgurumurthy.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Prajwal Gurumurthy
  url:               https://in.linkedin.com/in/prajwal-g-238a883b
  email:             prajwalg91@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/PrajwalGurumurthy/prajwalgurumurthy.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
